/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/coaches/{coach_id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list coach slots */
        get: operations["listCoachSlots"];
        put?: never;
        /** create coach slot */
        post: operations["createCoachSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list coaches */
        get: operations["listCoaches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list student slots */
        get: operations["listStudentSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/slots/{slot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** join slot */
        put: operations["joinSlot"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Coach: {
            id: number;
            name: string;
            slots: components["schemas"]["Slot"][];
        };
        Slot: {
            id: number;
            title?: string;
            phone?: string;
            start: string;
            end: string;
        };
        Student: {
            id: number;
            name: string;
            slots: components["schemas"]["Slot"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCoachSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coach_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Slot"][];
                    };
                };
            };
        };
    };
    createCoachSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coach_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slot: {
                        start: string;
                    };
                };
            };
        };
        responses: {
            /** @description successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Slot"];
                    };
                };
            };
        };
    };
    listCoaches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Coach"][];
                    };
                };
            };
        };
    };
    listStudentSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Slot"][];
                    };
                };
            };
        };
    };
    joinSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Slot"];
                    };
                };
            };
        };
    };
}
